# workflowの名前
name: Deploy to My Server

# どんな時にこのワークフローを実行するか
on:
  push:
    # mainブランチにプッシュされた時だけ実行
    branches:
      - main

# 実行するジョブ（処理のまとまり）
jobs:
  deploy:
    # 実行するOS環境を指定
    runs-on: debian-latest
    steps:
      # 1. GitHubリポジトリのコードをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. SSH接続してコマンドを実行
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          # SSH接続に必要な情報をGitHubのSecretsから持ってくる
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # サーバーで実行するコマンド
          script: |
            cd /DATA/AppData/crafty/servers/db973ccc-f0c3-4420-8cae-ac449dfa0737/world/datapacks/
            git pull
            # 他にも何か必要なコマンドがあれば、ここに書く
            # 例: npm installとか、サービスを再起動するコマンドとか
